django_app/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
# import hello.views as hello

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('hello/', hello.index),
    path('hello/', include('hello.urls')),
    path('blogapp/', include('blogapp.urls')),
    path('', include('photo.urls')),
    path('', include('accounts.urls')),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="password_reset.html"), name="password_reset"),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name="password_reset_sent.html"), name="password_reset_done"),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name="password_reset_form.html"), name="password_reset_confirm"),
    path('reset/done', auth_views.PasswordResetCompleteView.as_view(template_name="password_reset_done.html"), name="password_reset_complete"),
]

hello/urls.py
from django.urls import path
from . import views
from django.conf.urls import url
from .views import HelloView

urlpatterns = [
    url(r'form/7/', HelloView.as_view(), name="formseventh"),
    path('', views.index, name='index'),
    path('next', views.next, name='next'),
    path('form', views.form, name='form'),
    path('form/1/', views.formfirst, name='formfirst'),
    path('form/2/', views.formsecond, name='formsecond'),
    path('form/3/', views.formthird, name='formthird'),
    path('form/4/', views.formfourth, name='formfourth'),
    path('form/5/', views.formfifth, name='formfifth'),
    path('form/6/', views.formsixth, name='formsixth'),
    path('query', views.query, name='query'),
    path('queries/<int:id>/<nickname>/', views.queries, name='queries'),
    path('users', views.users, name='users'),
    path('users/userid', views.userid, name='userid'),
    path('manager', views.manager, name='manager'),
    path('manager/values', views.managervalues, name='managervalues'),
    path('manager/values/lim', views.managervalueslim, name='managervalueslim'),
    path('manager/values/list', views.managervalueslist, name='managervalueslist'),
    path('manager/values/others', views.managervaluesothers, name='managervaluesothers'),
    path('manager/queryset', views.managerqueryset, name='managerqueryset'),
    path('crud', views.crudindex, name='crudindex'),
    path('crud/create', views.create, name='create'),
    path('crud/create/meta', views.createmeta, name='createmeta'),
    path('crud/edit/<int:num>', views.edit, name='edit'),
    path('crud/delete/<int:num>', views.delete, name='delete'),
    path('find', views.find, name='find'),
    path('data', views.age, name='age'),
    path('data/reverse', views.agerev, name='agerev'),
    path('data/find', views.select, name="select"),
    path('data/syukei', views.syukei, name='syukei'),
    path('data/sqlquery', views.sqlquery, name='sqlquery'),
    path('check', views.check, name='check'),
    path('check/2', views.checktwo, name='checktwo'),
    path('checks', views.checktwo, name='checks'),
    path('page', views.page, name='page'),
    path('page/<int:num>', views.page, name='page'),
    path('message/', views.message, name='message'),
    path('message/<int:page>', views.message, name='message'),
    path('top', views.top, name='top'),
    path('top/<int:num>', views.top, name='top'),
]

hello/models.py
import re
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator, ValidationError

def number_only(value):
    if (re.match(r'^[0-9]*$', value) == None):
        raise ValidationError(
            '%(value)s is not Number!',
            params={'value': value},
        )

class Friend(models.Model):
    name = models.CharField(max_length=100)
    mail = models.EmailField(max_length=200)
    gender = models.BooleanField(null=True)
    age = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(150)])
    birthday = models.DateField()

    def __str__(self):
        return '<Friend: id=' + str(self.id) + ', ' + \
            self.name + '( ' + str(self.age) + ' )>'

class Message(models.Model):
    friend = models.ForeignKey(Friend, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    content = models.CharField(max_length=300)
    pub_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '<Message: id=' + str(self.id) + ', ' + \
            self.title + '( ' + str(self.pub_date) + ' )>'
    
    class Meta:
        ordering = ('pub_date',)

hello/forms.py
from django import forms
from .models import Friend, Message

class FirstForm(forms.Form):
    name = forms.CharField(label='name')
    mail = forms.EmailField(label='mail')
    age = forms.IntegerField(label='age')

class SecondForm(forms.Form):
    check = forms.BooleanField(label='Checkbox', required=False)

class ThirdForm(forms.Form):
    check = forms.NullBooleanField(label='Check')

class FourthForm(forms.Form):
    data = [
        ('値', 'ラベル'),
        ('one', 'item 1'),
        ('two', 'item 2'),
    ]
    choice = forms.ChoiceField(label='Choice', choices=data)

class FifthForm(forms.Form):
    data = [
        ('値', 'ラベル'),
        ('one', 'item 1'),
        ('two', 'item 2'),
    ]
    choice = forms.ChoiceField(label='Radio', choices=data, widget=forms.RadioSelect())

class SixthForm(forms.Form):
    data = [
        ('値', 'ラベル'),
        ('one', 'item 1'),
        ('two', 'item 2'),
    ]
    choice = forms.ChoiceField(label='List', choices=data, widget=forms.Select(attrs={'size': 3}))

class HelloForm(forms.Form):
    data = [
        ('値', 'ラベル'),
        ('one', 'item 1'),
        ('two', 'item 2'),
        ('three', 'item 3'),
        ('four', 'item 4'),
        ('five', 'item 5'),
    ]
    choice = forms.MultipleChoiceField(label='Multiple', choices=data, widget=forms.SelectMultiple(attrs={'size': 5}))

class IdForm(forms.Form):
    id = forms.IntegerField(label='ID')

class Create(forms.Form):
    name = forms.CharField(label='Name')
    mail = forms.EmailField(label='Email')
    gender = forms.NullBooleanField(label='Gender')
    age = forms.IntegerField(label='Age')
    birthday = forms.DateField(label='Birth')

class FriendForm(forms.ModelForm):
    class Meta:
        model = Friend
        fields = ['name','mail','gender','age','birthday']

class FindForm(forms.Form):
    find = forms.CharField(label='Find', required=False)

class CheckForm(forms.Form):
    str = forms.CharField(label='String')

    def clean(self):
        cleaned_data = super().clean()
        str = cleaned_data['str']
        if (str.lower().startswith('no')):
            raise forms.ValidationError('You input "NO"!')

class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['title', 'content', 'friend']

hello/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.generic import TemplateView
from .forms import HelloForm, FirstForm, SecondForm, ThirdForm, FourthForm, FifthForm, SixthForm, \
    IdForm, Create, FriendForm, FindForm, CheckForm, MessageForm
from .models import Friend, Message
from django.db.models import QuerySet, Count, Sum, Avg, Min, Max
from django.core.paginator import Paginator

def index(request):
    params = {
        'title': 'Index',
        'msg': 'これは、トップページです。',
        'goto': 'next',
        'form': 'form',
        'users': 'users',
        'manager': 'manager',
    }
    return render(request, 'hello/index.html', params)

# def index(request):
#     msg = request.GET['msg']
#     return HttpResponse('you typed: "' + msg + '".')

def query(request):
    if 'msg' in request.GET:
        msg = request.GET['msg']
        result = 'you typed: "' + msg + '".'
    else:
        result = 'please send msg parameter!'
    return HttpResponse(result)

def queries(request, id, nickname):
    result = 'your id: ' + str(id) + ', name: "' + nickname + '".'
    return HttpResponse(result)

def next(request):
    params = {
        'title': 'Next',
        'msg': 'これは、もう一つのページです。',
        'goto': 'index',
        'form': 'form',
        'users': 'users',
        'manager': 'manager',
    }
    return render(request, 'hello/index.html', params)

def form(request):
    params = {
        'title': 'Default',
        'msg': 'フォームトップページです。<br>クリックは無効ですよ。',
    }
    return render(request, 'hello/form.html', params)

def formfirst(request):
    params = {
        'title': 'Field',
        'msg': 'your data:',
        'form': FirstForm(),
    }
    if (request.method == 'POST'):
        params['msg'] = '名前：' + request.POST['name'] + \
            '<br>メール：' + request.POST['mail'] + \
            '<br>年齢：' + request.POST['age']
        params['form'] = FirstForm(request.POST)
    return render(request, 'hello/form.html', params)

def formsecond(request):
    params = {
        'title': 'Checkbox',
        'msg': None,
        'form': SecondForm(),
    }
    if (request.method == 'POST'):
        if ('check' in request.POST):
            params['msg'] = 'Checked!!'
        else:
            params['msg'] = 'not checked...'
        params['form'] = SecondForm(request.POST)
    return render(request, 'hello/form.html', params)

def formthird(request):
    params = {
        'title': 'NullBoolean',
        'msg': None,
        'form': ThirdForm(),
    }
    if (request.method == 'POST'):
        chk = request.POST['check']
        params['msg'] = 'you selected: "' + chk + '".'
        params['form'] = ThirdForm(request.POST)
    return render(request, 'hello/form.html', params)

def formfourth(request):
    params = {
        'title': 'PullDown',
        'msg': None,
        'form': FourthForm(),
    }
    if (request.method == 'POST'):
        ch = request.POST['choice']
        params['msg'] = 'you selected: "' + ch + '".'
        params['form'] = FourthForm(request.POST)
    return render(request, 'hello/form.html', params)

def formfifth(request):
    params = {
        'title': 'Radio',
        'msg': None,
        'form': FifthForm(),
    }
    if (request.method == 'POST'):
        ch = request.POST['choice']
        params['msg'] = 'you selected: "' + ch + '".'
        params['form'] = FifthForm(request.POST)
    return render(request, 'hello/form.html', params)

def formsixth(request):
    params = {
        'title': 'List',
        'msg': None,
        'form': SixthForm(),
    }
    if (request.method == 'POST'):
        ch = request.POST['choice']
        params['msg'] = 'you selected: "' + ch + '".'
        params['form'] = FifthForm(request.POST)
    return render(request, 'hello/form.html', params)

class HelloView(TemplateView):
    def __init__(self):
        self.params = {
            'title': 'Multiple',
            'msg': None,
            'form': HelloForm(),
        }
    
    def get(self, request):
        return render(request, 'hello/form.html', self.params)
    
    def post(self, request):
        ch = request.POST.getlist('choice')
        result = '<ol><b>selected:</b>'
        for i in ch:
            result += '<li>' + i + '</li>'
        result += '</ol>'
        self.params['msg'] = result
        self.params['form'] = HelloForm(request.POST)
        return render(request, 'hello/form.html', self.params)

def users(request):
    data = Friend.objects.all()
    params = {
        'title': 'Userall',
        'message': 'all freinds.',
        'data': data,
    }
    return render(request, 'hello/users.html', params)

def userid(request):
    params = {
        'title': 'Userid',
        'message': 'all friends.',
        'form': IdForm(),
        'data': [],
    }
    if (request.method == 'POST'):
        num = request.POST['id']
        item = Friend.objects.get(id=num)
        params['data'] = [item]
        params['form'] = IdForm(request.POST)
    else:
        params['data'] = Friend.objects.all()
    return render(request, 'hello/users.html', params)

def manager(request):
    data = Friend.objects.all()
    params = {
        'title': 'Default',
        'data': data,
    }
    return render(request, 'hello/manager/index.html', params)

def managervalues(request):
    data = Friend.objects.all().values()
    params = {
        'title': 'Values',
        'data': data,
    }
    return render(request, 'hello/manager/index.html', params)

def managervalueslim(request):
    data = Friend.objects.all().values('id', 'name')
    params = {
        'title': 'ValuesLim',
        'data': data,
    }
    return render(request, 'hello/manager/index.html', params)

def managervalueslist(request):
    data = Friend.objects.all().values_list('id', 'name', 'age')
    params = {
        'title': 'ValuesList',
        'data': data,
    }
    return render(request, 'hello/manager/index.html', params)

def managervaluesothers(request):
    num = Friend.objects.all().count()
    first = Friend.objects.all().first()
    last = Friend.objects.all().last()
    data = [num, first, last]
    params = {
        'title': 'ValuesOthers',
        'data': data,
    }
    return render(request, 'hello/manager/index.html', params)

def __new_str__(self):
    result = ''
    for item in self:
        result += '<tr>'
        for k in item:
            result += '<td>' + str(k) + '=' + str(item[k]) + '</td>'
        result += '</tr>'
    return result

QuerySet.__str__ = __new_str__

def managerqueryset(request):
    data = Friend.objects.all().values('id', 'name', 'age')
    params = {
        'title': 'QuerySet',
        'data': data,
    }
    return render(request, 'hello/manager/queryset.html', params)

def crudindex(request):
    data = Friend.objects.all()
    params = {
        'title': 'Default',
        'data': data,
    }
    return render(request, 'hello/crud/index.html', params)

def create(request):
    params = {
        'title': 'Create',
        'form': Create(),
    }
    if (request.method == 'POST'):
        name = request.POST['name']
        mail = request.POST['mail']
        gender = 'gender' in request.POST
        age = int(request.POST['age'])
        birth = request.POST['birthday']
        friend = Friend(name=name, mail=mail, gender=gender, age=age, birthday=birth)
        friend.save()
        return redirect(to='/hello/crud')
    return render(request, 'hello/crud/create.html', params)

def createmeta(request):
    if (request.method == 'POST'):
        obj = Friend()
        friend = FriendForm(request.POST, instance=obj)
        friend.save()
        return redirect(to='/hello/crud')
    params = {
        'title': 'CreateMeta',
        'form': FriendForm(),
    }
    return render(request, 'hello/crud/create.html', params)

def edit(request, num):
    obj = Friend.objects.get(id=num)
    if (request.method == 'POST'):
        friend = FriendForm(request.POST, instance=obj)
        friend.save()
        return redirect(to='/hello/update')
    params = {
        'title': 'Update',
        'id': num,
        'form': FriendForm(instance=obj)
    }
    return render(request, 'hello/crud/edit.html', params)

def delete(request, num):
    friend = Friend.objects.get(id=num)
    if (request.method == 'POST'):
        friend.delete()
        return redirect(to='/hello/crud')
    params = {
        'title': 'Delete',
        'id': num,
        'obj': friend
    }
    return render(request, 'hello/crud/delete.html', params)

def find(request):
    if (request.method == 'POST'):
        msg = 'serch result:'
        form = FindForm(request.POST)
        str = request.POST['find']
        data = Friend.objects.filter(name__icontains=str)
    else:
        msg = 'serch words ...'
        form = FindForm()
        data = Friend.objects.all()
    params = {
        'title': 'Find',
        'message': msg,
        'form': form,
        'data': data,
    }
    return render(request, 'hello/find.html', params)

def age(request):
    data = Friend.objects.all().order_by('age')
    params = {
        'title': 'Hello',
        'message': '',
        'data': data,
    }
    return render(request, 'hello/data/index.html', params)

def agerev(request):
    data = Friend.objects.all().order_by('age').reverse()
    params = {
        'title': 'Hello',
        'message': '',
        'data': data,
    }
    return render(request, 'hello/data/index.html', params)

def select(request):
    if (request.method == 'POST'):
        msg = 'serch result:'
        form = FindForm(request.POST)
        str = request.POST['find']
        list = str.split()
        data = Friend.objects.all()[int(list[0]):int(list[1])]
    else:
        msg = 'serch words ...'
        form = FindForm()
        data = Friend.objects.all()
    params = {
        'title': 'Find',
        'message': msg,
        'form': form,
        'data': data,
        'path': 'select',
    }

hello/templates/hello/check.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'hello/css/style.css' %}" />
</head>
<body>
    <h1>{{ title }}</h1>
    <p>{{ message }}</p>
    <table>
        <form action="{% url 'check' %}" method="post">
        {% csrf_token %}
        {{ form.as_table }}
        <tr>
            <td></td>
            <td>
                <input type="submit" value="click">
            </td>
        </tr>
    </table>
</body>
</html>

hello/templates/hello/checks.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'hello/css/style.css' %}" />
</head>
<body>
    <h1>{{ title }}</h1>
    <p>{{ message }}</p>
    <hr>
    <ol>
    {% for item in form %}
    <li>
        {{ item.name }} ({{ item.value }}) : {{ item.errors.as_text }}
    </li>
    {% endfor %}
    </ol>
    <table>
        <form action="{% url 'checks' %}" method="post">
        {% csrf_token %}
        <tr>
            <th>名前</th>
            <td>{{ form.name }}</td>
        </tr>
        <tr>
            <th>メール</th>
            <td>{{ form.mail }}</td>
        </tr>
        <tr>
            <th>性別</th>
            <td>{{ form.gender }}</td>
        </tr>
        <tr>
            <th>年齢</th>
            <td>{{ form.age }}</td>
        </tr>
        <tr>
            <th>誕生日</th>
            <td>{{ form.birthday }}</td>
        </tr>
        <tr>
            <td></td>
            <td>
                <input type="submit" value="click">
            </td>
        </tr>
    </table>
</body>
</html>

hello/templates/hello/create.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'hello/css/style.css' %}" />
</head>
<body>
    <h1>Hello/{{ title }}</h1>
    <table>
        <form action="{% url 'create' %}" method="post">
            {% csrf_token %}
            {{ form.as_table }}
            <tr>
                <td></td>
                <td><input type="submit" value="click"></td>
            </tr>
        </form>
    </table>
</body>
</html>

hello/templates/hello/find.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'hello/css/style.css' %}" />
</head>
<body>
    <h1>Hello/CRUD/{{ title }}</h1>
    <p>{{ message|safe }}</p>
    <table>
        <form action="{% url 'find' %}" method="post">
            {% csrf_token %}
            {{ form.as_table }}
            <tr>
                <td></td>
                <td><input type="submit" value="click"></td>
            </tr>
        </form>
    </table>
    <hr>
    <table>
        <tr>
            <th>data</th>
            <th></th>
            <th></th>
        </tr>
    {% for item in data %}    
        <tr>
            <td>{{ item }}</td>
            <td><a href="{% url 'edit' item.id %}">Edit</a></td>
            <td><a href="{% url 'delete' item.id %}">Delete</a></td>
        </tr>
    {% endfor %}
    </table>
</body>
</html>

hello/templates/hello/form.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'hello/css/style.css' %}" />
</head>
<body>
    <h1>Hello/Form/{{ title }}</h1>
    <div class="parent">
        <div>
            <p><a href="{% url 'form' %}">FormDefault</a></p>
            <p><a href="{% url 'formfirst' %}">FormField</a></p>
            <p><a href="{% url 'formsecond' %}">FormCheckbox</a></p>
            <p><a href="{% url 'formthird' %}">FormNullBooiean</a></p>
            <p><a href="{% url 'formfourth' %}">FormPullDown</a></p>
            <p><a href="{% url 'formfifth' %}">FormRadio</a></p>
            <p><a href="{% url 'formsixth' %}">FormList</a></p>
            <p><a href="{% url 'formseventh' %}">FormMultiple</a></p>
        </div>
        <div>
            <p>{{ msg|safe }}</p>
            <table>
            <form method="post">
                {% csrf_token %}
                {{ form.as_table }}
                <tr>
                    <td></td>
                    <td><input type="submit" value="click"></td>
                </tr>
            </form>
            </table>
        </div>
    </div>
</body>
</html>

hello/templates/hello/index.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'hello/css/style.css' %}" />
</head>
<body>
    <h1>Hello/{{ title }}</h1>
    <p>{{ msg }}</p>
    <p><a href="{% url goto %}">{{ goto }}</a></p>
    <p><a href="{% url form %}">{{ form }}</a></p>
    <p><a href="{% url users %}">{{ users }}</a></p>
    <p><a href="{% url manager %}">{{ manager }}</a></p>
    <p><a href="{% url 'crudindex' %}">crud</a></p>
    <p><a href="{% url 'find' %}">find</a></p>
    <p><a href="{% url 'check' %}">check</a></p>
    <p><a href="{% url 'checks' %}">checks</a></p>
    <p><a href="{% url 'page' %}">page</a></p>
    <p><a href="{% url 'message' %}">message</a></p>
</body>
</html>

hello/templates/hello/manager.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'hello/css/style.css' %}" />
</head>
<body>
    <h1>Hello/Manager/{{ title }}</h1>
    <p><a href="{% url 'manager' %}">ManagerDefault</a></p>
    <p><a href="{% url 'managervalues' %}">ManagerValues</a></p>
    <p><a href="{% url 'managervalueslim' %}">ManagerValuesLim</a></p>
    <p><a href="{% url 'managervalueslist' %}">ManagerValuesList</a></p>
    <p><a href="{% url 'managervaluesothers' %}">ManagerValuesOthers</a></p>
    <p><a href="{% url 'managerqueryset' %}">ManagerQuerySet</a></p>
    <table>
        <tr>
            <th>data</th>
        </tr>
    {% for item in data %}
        <tr>
            <td>{{ item }}</td>
        </tr>
    {% endfor %}
    </table>
</body>
</html>

hello/templates/hello/message.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'hello/css/style.css' %}" />
</head>
<body>
    <h1>{{ title }}</h1>
    <table>
        <form action="{% url 'message' %}" method="post">
            {% csrf_token %}
            {{ form.as_table }}
            <tr>
                <td></td>
                <td><input type="submit" value="send"></td>
            </tr>
        </form>
    </table>
    <hr>
    <table>
        <tr>
            <th>title</th>
            <th>name</th>
            <th>datetime</th>
        </tr>
    {% for item in data %}
        <tr>
            <td>{{ item.title }}</td>
            <td>{{ item.friend.name }}</td>
            <td>{{ item.pub_date }}</td>
        </tr>
    {% endfor %}
    </table>
    <div class="pagination">
        {% if data.has_previous %}
            <a href="{% url 'message' %}/{{ data.previous_page_number }}">&laquo;prev</a>
        {% endif %}
        {% if data.has_next %}
            <a href="{% url 'page' %}/{{ data.next_page_number }}">next&raquo;</a>
        {% endif %}
    </div>
</body>
</html>

hello/templates/hello/top.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'hello/css/style.css' %}" />
</head>
<body>
    <h1>{{ title }}</h1>
    <p>{{ message|safe }}</p>
    <table>
        <tr>
            <th>id</th>
            <th>name</th>
            <th>age</th>
            <th>mail</th>
            <th>birthday</th>
            <th>Message</th>
        </tr>
    {% for item in data %}
        <tr>
            <td>{{ item.id }}</td>
            <td>{{ item.name }}</td>
            <td>{{ item.age }}</td>
            <td>{{ item.mail }}</td>
            <td>{{ item.birthday }}</td>
            <td>
                <ul>
                {% for ob in item.message_set.all %}
                    <li>{{ ob.title }}</li>
                {% endfor %}
                </ul>
            </td>
        </tr>
    {% endfor %}
    </table>
    <div class="pagination">
        {% if data.has_previous %}
            <a href="{% url 'top' %}">&laquo;first</a>
            <a href="{% url 'top' %}/{{ data.previous_page_number }}">&laquo;prev</a>
        {% endif %}
        <span class="current">
            [{{ data.number }}/{{ data.paginator.num_pages }}]
        </span>
        {% if data.has_next %}
            <a href="{% url 'top' %}/{{ data.next_page_number }}">next&raquo;</a>
            <a href="{% url 'top' %}/{{ data.paginator.num_pages }}">last&raquo;</a>
        {% endif %}
    </div>
</body>
</html>