blogapp/urls.py
from django.urls import path
from . import views

app_name = 'blogapp'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('blog-detail/<int:pk>/', views.BlogDetail.as_view(), name='blog_detail'),
    path('science-list/', views.ScienceView.as_view(), name='science_list'),
    path('dailylife-list/', views.DailylifeView.as_view(), name='dailylife_list'),
    path('music-list/', views.MusicView.as_view(), name='music_list'),
    path('contact/', views.ContactView.as_view(), name='contact')
]

django_app/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
# import hello.views as hello

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('hello/', hello.index),
    path('hello/', include('hello.urls')),
    path('blogapp/', include('blogapp.urls')),
    path('', include('photo.urls')),
    path('', include('accounts.urls')),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="password_reset.html"), name="password_reset"),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name="password_reset_sent.html"), name="password_reset_done"),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name="password_reset_form.html"), name="password_reset_confirm"),
    path('reset/done', auth_views.PasswordResetCompleteView.as_view(template_name="password_reset_done.html"), name="password_reset_complete"),
]

hello/urls.py
from django.urls import path
from . import views
from django.conf.urls import url
from .views import HelloView

urlpatterns = [
    url(r'form/7/', HelloView.as_view(), name="formseventh"),
    path('', views.index, name='index'),
    path('next', views.next, name='next'),
    path('form', views.form, name='form'),
    path('form/1/', views.formfirst, name='formfirst'),
    path('form/2/', views.formsecond, name='formsecond'),
    path('form/3/', views.formthird, name='formthird'),
    path('form/4/', views.formfourth, name='formfourth'),
    path('form/5/', views.formfifth, name='formfifth'),
    path('form/6/', views.formsixth, name='formsixth'),
    path('query', views.query, name='query'),
    path('queries/<int:id>/<nickname>/', views.queries, name='queries'),
    path('users', views.users, name='users'),
    path('users/userid', views.userid, name='userid'),
    path('manager', views.manager, name='manager'),
    path('manager/values', views.managervalues, name='managervalues'),
    path('manager/values/lim', views.managervalueslim, name='managervalueslim'),
    path('manager/values/list', views.managervalueslist, name='managervalueslist'),
    path('manager/values/others', views.managervaluesothers, name='managervaluesothers'),
    path('manager/queryset', views.managerqueryset, name='managerqueryset'),
    path('crud', views.crudindex, name='crudindex'),
    path('crud/create', views.create, name='create'),
    path('crud/create/meta', views.createmeta, name='createmeta'),
    path('crud/edit/<int:num>', views.edit, name='edit'),
    path('crud/delete/<int:num>', views.delete, name='delete'),
    path('find', views.find, name='find'),
    path('data', views.age, name='age'),
    path('data/reverse', views.agerev, name='agerev'),
    path('data/find', views.select, name="select"),
    path('data/syukei', views.syukei, name='syukei'),
    path('data/sqlquery', views.sqlquery, name='sqlquery'),
    path('check', views.check, name='check'),
    path('check/2', views.checktwo, name='checktwo'),
    path('checks', views.checktwo, name='checks'),
    path('page', views.page, name='page'),
    path('page/<int:num>', views.page, name='page'),
    path('message/', views.message, name='message'),
    path('message/<int:page>', views.message, name='message'),
    path('top', views.top, name='top'),
    path('top/<int:num>', views.top, name='top'),
]

blogapp/models.py
from django.db import models

# Create your models here.

class BlogPost(models.Model):
    CATEGORY = (('science', '科学のこと'),
                ('dailylife', '日常のこと'),
                ('music', '音楽のこと'))
    
    title = models.CharField(
        verbose_name='タイトル',
        max_length=200
    )

    content = models.TextField(
        verbose_name='本文'
    )

    posted_at = models.DateTimeField(
        verbose_name='投稿日時',
        auto_now_add=True
    )

    category = models.CharField(
        verbose_name='カテゴリー',
        max_length=50,
        choices=CATEGORY
    )

    def __str__(self):
        return self.title

blogapp/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField(label='お名前')
    email = forms.EmailField(label='メールアドレス')
    title = forms.CharField(label='件名')
    message = forms.CharField(label='メッセージ', widget=forms.Textarea)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs['placeholder'] = 'お名前を入力してください'
        self.fields['name'].widget.attrs['class'] = 'form-control'
        self.fields['email'].widget.attrs['placeholder'] = 'メールアドレスを入力してください'
        self.fields['email'].widget.attrs['class'] = 'form-control'
        self.fields['title'].widget.attrs['placeholder'] = 'タイトルを入力してください'
        self.fields['title'].widget.attrs['class'] = 'form-control'
        self.fields['message'].widget.attrs['placeholder'] = 'メッセージを入力してください'
        self.fields['message'].widget.attrs['class'] = 'form-control'
        

blogapp/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, FormView
from django.urls import reverse_lazy
from .forms import ContactForm
from django.contrib import messages
from django.core.mail import EmailMessage
from .models import BlogPost

# Create your views here.

class Index(ListView):
    template_name = 'index.html'
    context_object_name = 'orderby_records'
    queryset = BlogPost.objects.order_by('-posted_at')
    paginate_by = 4

class BlogDetail(DetailView):
    template_name = 'post.html'
    model = BlogPost

class ScienceView(ListView):
    template_name = 'science_list.html'
    model = BlogPost
    context_object_name = 'science_records'
    queryset = BlogPost.objects.filter(category='science').order_by('-posted_at')
    paginate_by = 2

class DailylifeView(ListView):
    template_name = 'dailylife_list.html'
    model = BlogPost
    context_object_name = 'dailylife_records'
    queryset = BlogPost.objects.filter(category='dailylife').order_by('-posted_at')
    paginate_by = 2

class MusicView(ListView):
    template_name = 'music_list.html'
    model = BlogPost
    context_object_name = 'music_records'
    queryset = BlogPost.objects.filter(category='music').order_by('-posted_at')
    paginate_by = 2

class ContactView(FormView):
    template_name = 'contact.html'
    form_class = ContactForm
    success_url = reverse_lazy('blogapp:contact')

    def form_valid(self, form):
        name = form.cleaned_data['name']
        email = form.cleaned_data['email']
        title = form.cleaned_data['title']
        message = form.cleaned_data['message']
        subject = 'お問い合わせ：{}'.format(title)
        message = \
          '送信者：{0}\nメールアドレス：{1}\nタイトル：{2}\nメッセージ：\n{3}'\
          .format(name, email, title, message)
        from_email = 'suematsu.hiroki.fw@gmail.com'
        to_list = ['suematsu.hiroki.fw@gmail.com']
        message = EmailMessage(subject=subject,
                               body=message,
                               from_email=from_email,
                               to=to_list,
                               )
        message.send()
        messages.success(
            self.request, 'お問い合わせは正常に送信されました。'
        )
        return super().form_valid(form)

blogapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block title %}{% endblock %}</title>
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'blogapp:index' %}">Django's Blog</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blogapp:index' %}">Home</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blogapp:science_list' %}">SCIENCE</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blogapp:dailylife_list' %}">DAILYLIFE</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blogapp:music_list' %}">MUSIC</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blogapp:contact' %}">CONTACT</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Header-->
        <!-- <header class="masthead" style="background-image: url({% static 'assets/img/home-bg.jpg' %})">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>Django's Blog</h1>
                            <span class="subheading">A Blog Theme by Start Bootstrap</span>
                        </div>
                    </div>
                </div>
            </div>
        </header> -->
        {% block header %}{% endblock %}
        <!-- Main Content-->
        <!-- <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    {% for record in orderby_records %} -->
                    <!-- Post preview-->
                    <!-- <div class="post-preview">
                        <a href="{% url 'blogapp:blog_detail' record.pk %}">
                            <h2 class="post-title">{{ record.title }}</h2>
                            <h3 class="post-subtitle">
                                <span style="font-size: 14px;">{{ record.content|truncatechars:50 }}</span>
                            </h3>
                        </a>
                        <p class="post-meta">
                            Posted by
                            <a href="#">Django's Blog</a>
                            {{ record.posted_at }}に投稿 / カテゴリ：{{ record.category }}
                        </p>
                    </div> -->
                    <!-- Divider-->
                    <!-- <hr class="my-4" />
                    {% endfor %} -->
                    <!-- Pager-->
                    <!-- <div class="d-flex justify-content-end mb-4"><a class="btn btn-primary text-uppercase" href="#!">Older Posts →</a></div>
                </div>
            </div>
        </div> -->
        {% block contents %}{% endblock %}
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="https://twitter.com/">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="https://www.facebook.com/">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="https://github.co.jp/">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Django's Blog 2023</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

blogapp/templates/contact.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Django's Blog - Contact{% endblock %}

{% block header %}
<header class="masthead" style="background-image: url({% static 'assets/img/contact-bg.jpg' %})">
  <div class="container position-relative px-4 px-lg-5">
      <div class="row gx-4 gx-lg-5 justify-content-center">
          <div class="col-md-10 col-lg-8 col-xl-7">
              <div class="page-heading">
                  <h1>Contact Me</h1>
                  <span class="subheading">Have questions? I have answers.</span>
              </div>
          </div>
      </div>
  </div>
</header>
{% endblock %}

{% block contents %}
<main class="mb-4">
  <div class="container px-4 px-lg-5">
      <div class="row gx-4 gx-lg-5 justify-content-center">
          <div class="col-md-10 col-lg-8 col-xl-7">
              <strong>連絡を取りたい場合は、以下のフォームに記入してメッセージを送信してください。</strong>
              {% if messages %}
              <ul class="list-unstyled" style="list-style: none;">
                {% for message in messages %}
                  <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>
                    {{ message }}
                  </li>
                {% endfor %}
              </ul>
              {% endif %}
              <div class="my-5">
                  <!-- * * * * * * * * * * * * * * *-->
                  <!-- * * SB Forms Contact Form * *-->
                  <!-- * * * * * * * * * * * * * * *-->
                  <!-- This form is pre-integrated with SB Forms.-->
                  <!-- To make this form functional, sign up at-->
                  <!-- https://startbootstrap.com/solution/contact-forms-->
                  <!-- to get an API token!-->
                  <form id="contactForm" data-sb-form-api-token="API_TOKEN" method="post">
                      {% csrf_token %}
                      {% for field in form %}
                        <div class="form-floating">
                          <div class="form-group floating-label-from-group controls">
                            {{ field.label_tag }}
                            {{ field }}
                            <p class="help-block text-danger"></p>
                          </div>
                        </div>
                      {% endfor %}
                      <br />
                      <!-- Submit Button-->
                      <button class="btn btn-primary" id="sendMessageButton" type="submit">Send</button>
                  </form>
              </div>
          </div>
      </div>
  </div>
</main>
{% endblock %}

blogapp/templates/dailylife_list.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Django's Blog - Dailylife{% endblock %}

{% block header %}
<header class="masthead" style="background-image: url({% static 'assets/img/home-bg.jpg' %})">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>Django's Blog</h1>
                    <span class="subheading">Dailylifeカテゴリの記事一覧</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}

{% block contents %}
<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            {% for record in dailylife_records %}
            <!-- Post preview-->
            <div class="post-preview">
                <a href="{% url 'blogapp:blog_detail' record.pk %}">
                    <h2 class="post-title">{{ record.title }}</h2>
                    <h3 class="post-subtitle">
                        <span style="font-size: 14px;">{{ record.content|truncatechars:50 }}</span>
                    </h3>
                </a>
                <p class="post-meta">
                    Posted by
                    <a href="#">Django's Blog</a>
                    {{ record.posted_at }}に投稿 / カテゴリ：{{ record.category }}
                </p>
            </div>
            <!-- Divider-->
            <hr class="my-4" />
            {% endfor %}
            {% include 'pagination.html' %}
        </div>
    </div>
</div>
{% endblock %}

blogapp/templates/index.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Django's Blog{% endblock %}

{% block header %}
<header class="masthead" style="background-image: url({% static 'assets/img/home-bg.jpg' %})">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>Django's Blog</h1>
                    <span class="subheading">A Blog Theme by Start Bootstrap</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}

{% block contents %}
<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            {% for record in orderby_records %}
            <!-- Post preview-->
            <div class="post-preview">
                <a href="{% url 'blogapp:blog_detail' record.pk %}">
                    <h2 class="post-title">{{ record.title }}</h2>
                    <h3 class="post-subtitle">
                        <span style="font-size: 14px;">{{ record.content|truncatechars:50 }}</span>
                    </h3>
                </a>
                <p class="post-meta">
                    Posted by
                    <a href="#">Django's Blog</a>
                    {{ record.posted_at }}に投稿 / カテゴリ：{{ record.category }}
                </p>
            </div>
            <!-- Divider-->
            <hr class="my-4" />
            {% endfor %}
            <!-- Pager-->
            <div class="d-flex justify-content-end mb-4"><a class="btn btn-primary text-uppercase" href="#!">Older Posts →</a></div>
        </div>
    </div>
</div>
{% endblock %}

blogapp/templates/music_list.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Django's Blog - Music{% endblock %}

{% block header %}
<header class="masthead" style="background-image: url({% static 'assets/img/home-bg.jpg' %})">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>Django's Blog</h1>
                    <span class="subheading">Musicカテゴリの記事一覧</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}

{% block contents %}
<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            {% for record in music_records %}
            <!-- Post preview-->
            <div class="post-preview">
                <a href="{% url 'blogapp:blog_detail' record.pk %}">
                    <h2 class="post-title">{{ record.title }}</h2>
                    <h3 class="post-subtitle">
                        <span style="font-size: 14px;">{{ record.content|truncatechars:50 }}</span>
                    </h3>
                </a>
                <p class="post-meta">
                    Posted by
                    <a href="#">Django's Blog</a>
                    {{ record.posted_at }}に投稿 / カテゴリ：{{ record.category }}
                </p>
            </div>
            <!-- Divider-->
            <hr class="my-4" />
            {% endfor %}
            {% include 'pagination.html' %}
        </div>
    </div>
</div>
{% endblock %}

blogapp/templates/pagination.html
<ul class="pagination" style="justify-content: center;">
  {% if page_obj.has_previous %}
  <li class="page-item">
    <a
      class="page-link"
      href="?page={{ page_obj.previous_page_number }}"
      aria-label="Previous"
    >
      <span aria-hidden="true">&laquo;</span>
    </a>
  </li>
  {% endif %}

  {% for num in page_obj.paginator.page_range %}
    {% if page_obj.number == num %}
    <li class="page-item active">
      <span class="page-link">{{ num }}</span>
    </li>
    {% else %}
    <li class="page-item">
      <a class="page-link" href="?page={{ num }}">{{ num }}</a>
    </li>
    {% endif %}
  {% endfor %}

  {% if page_obj.has_next %}
  <li class="page-item">
    <a
      class="page-link"
      href="?page={{ page_obj.next_page_number }}"
      aria-label="Next"
    >
      <span aria-hidden="true">&raquo;</span>
    </a>
  </li>
  {% endif %}
</ul>

blogapp/templates/post.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Django's Blog{% endblock %}

{% block header %}
<header class="masthead" style="background-image: url({% static 'assets/img/post-bg.jpg' %})">
  <div class="container position-relative px-4 px-lg-5">
      <div class="row gx-4 gx-lg-5 justify-content-center">
          <div class="col-md-10 col-lg-8 col-xl-7">
              <div class="post-heading">
                  <h1>{{ object.title }}</h1>
                  <h2 class="subheading">{{ object.content|truncatechars:30 }}</h2>
                  <span class="meta">
                      Posted by
                      <a href="{% url 'blogapp:index' %}">Django's Blog</a>
                      {{ object.posted_at }}に投稿 / カテゴリ：{{ object.category }}
                  </span>
              </div>
          </div>
      </div>
  </div>
</header>
{% endblock %}

{% block contents %}
<article class="mb-4">
  <div class="container px-4 px-lg-5">
      <div class="row gx-4 gx-lg-5 justify-content-center">
          <div class="col-md-10 col-lg-8 col-xl-7">
              <p>{{ object.content }}</p>
          </div>
      </div>
  </div>
</article>
<hr />
{% endblock %}

blogapp/templates/science_list.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Django's Blog - Science{% endblock %}

{% block header %}
<header class="masthead" style="background-image: url({% static 'assets/img/home-bg.jpg' %})">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>Django's Blog</h1>
                    <span class="subheading">Scienceカテゴリの記事一覧</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}

{% block contents %}
<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            {% for record in science_records %}
            <!-- Post preview-->
            <div class="post-preview">
                <a href="{% url 'blogapp:blog_detail' record.pk %}">
                    <h2 class="post-title">{{ record.title }}</h2>
                    <h3 class="post-subtitle">
                        <span style="font-size: 14px;">{{ record.content|truncatechars:50 }}</span>
                    </h3>
                </a>
                <p class="post-meta">
                    Posted by
                    <a href="#">Django's Blog</a>
                    {{ record.posted_at }}に投稿 / カテゴリ：{{ record.category }}
                </p>
            </div>
            <!-- Divider-->
            <hr class="my-4" />
            {% endfor %}
            {% include 'pagination.html' %}
        </div>
    </div>
</div>
{% endblock %}