accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('signup_success', views.SignUpSuccessView.as_view(), name='signup_success'),
    path('login/', auth_views.LoginView.as_view(template_name="login.html"), name="login"),
    path('logout/', auth_views.LogoutView.as_view(template_name="logout.html"), name="logout"),
]

django_app/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
# import hello.views as hello

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('hello/', hello.index),
    path('hello/', include('hello.urls')),
    path('blogapp/', include('blogapp.urls')),
    path('', include('photo.urls')),
    path('', include('accounts.urls')),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="password_reset.html"), name="password_reset"),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name="password_reset_sent.html"), name="password_reset_done"),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name="password_reset_form.html"), name="password_reset_confirm"),
    path('reset/done', auth_views.PasswordResetCompleteView.as_view(template_name="password_reset_done.html"), name="password_reset_complete"),
]

hello/urls.py
from django.urls import path
from . import views
from django.conf.urls import url
from .views import HelloView

urlpatterns = [
    url(r'form/7/', HelloView.as_view(), name="formseventh"),
    path('', views.index, name='index'),
    path('next', views.next, name='next'),
    path('form', views.form, name='form'),
    path('form/1/', views.formfirst, name='formfirst'),
    path('form/2/', views.formsecond, name='formsecond'),
    path('form/3/', views.formthird, name='formthird'),
    path('form/4/', views.formfourth, name='formfourth'),
    path('form/5/', views.formfifth, name='formfifth'),
    path('form/6/', views.formsixth, name='formsixth'),
    path('query', views.query, name='query'),
    path('queries/<int:id>/<nickname>/', views.queries, name='queries'),
    path('users', views.users, name='users'),
    path('users/userid', views.userid, name='userid'),
    path('manager', views.manager, name='manager'),
    path('manager/values', views.managervalues, name='managervalues'),
    path('manager/values/lim', views.managervalueslim, name='managervalueslim'),
    path('manager/values/list', views.managervalueslist, name='managervalueslist'),
    path('manager/values/others', views.managervaluesothers, name='managervaluesothers'),
    path('manager/queryset', views.managerqueryset, name='managerqueryset'),
    path('crud', views.crudindex, name='crudindex'),
    path('crud/create', views.create, name='create'),
    path('crud/create/meta', views.createmeta, name='createmeta'),
    path('crud/edit/<int:num>', views.edit, name='edit'),
    path('crud/delete/<int:num>', views.delete, name='delete'),
    path('find', views.find, name='find'),
    path('data', views.age, name='age'),
    path('data/reverse', views.agerev, name='agerev'),
    path('data/find', views.select, name="select"),
    path('data/syukei', views.syukei, name='syukei'),
    path('data/sqlquery', views.sqlquery, name='sqlquery'),
    path('check', views.check, name='check'),
    path('check/2', views.checktwo, name='checktwo'),
    path('checks', views.checktwo, name='checks'),
    path('page', views.page, name='page'),
    path('page/<int:num>', views.page, name='page'),
    path('message/', views.message, name='message'),
    path('message/<int:page>', views.message, name='message'),
    path('top', views.top, name='top'),
    path('top/<int:num>', views.top, name='top'),
]

photo/urls.py
from django.urls import path
from . import views

app_name = "photo"

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
]

photo/models.py
from django.db import models

# Create your models here.

photo/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

# Create your views here.

class IndexView(TemplateView):
    template_name = 'index_p.html'

photo/templates/base.html
{% load static %}

<!doctype html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>{% block title %}{% endblock %}</title>
    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
  </head>
  <body>
    <header>
      <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
          <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
              <h4 class="text-white">お気に入りを見つけよう！</h4>
              <p class="text-muted">
                誰でも参加できる写真投稿サイトです。
                自分で撮影した写真なら何でもOK
                でも、カテゴリに属する写真に限ります。
                コメントもつけてください！
              </p>
            </div>
            <div class="col-sm-4 offset-md-1 py-4">
              <h4 class="text-white">Contact</h4>
              <ul class="list-unstyled">
                <li><a href="#" class="text-white">サインアップ</a></li>
                <li><a href="#" class="text-white">ログイン</a></li>
                <li><a href="#" class="text-white">Email me</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container">
          <a href="{% url 'photo:index' %}" class="navbar-brand d-flex align-items-center">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2" viewBox="0 0 24 24"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>
            <strong>Photo Gallery</strong>
          </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
      </div>
    </header>

    <main>
    {% block contents %}{% endblock %}
    </main>

    <footer class="text-muted py-5">
      <div class="container">
        <p class="float-end mb-1">
          <a href="#">Back to top</a>
        </p>
        <p class="mb-1">Photo Gallery is &copy; Bootstrap, but please post a lot!</p>
      </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

  </body>
</html>

photo/templates/base_p.html
{% load static %}

<!doctype html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>{% block title %}{% endblock %}</title>
    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
  </head>
  <body>
    <header>
      <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
          <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
              <h4 class="text-white">お気に入りを見つけよう！</h4>
              <p class="text-muted">
                誰でも参加できる写真投稿サイトです。
                自分で撮影した写真なら何でもOK
                でも、カテゴリに属する写真に限ります。
                コメントもつけてください！
              </p>
            </div>
            <div class="col-sm-4 offset-md-1 py-4">
              <h4 class="text-white">Contact</h4>
              <ul class="list-unstyled">
                {% if user.is_authenticated %}
                  <li><a href="#" class="text-white">マイページ</a></li>
                  <li><a href="{% url 'accounts:logout' %}" class="text-white">ログアウト</a></li>
                  <li><a href="{% url 'password_reset' %}" class="text-white">パスワード変更</a></li>
                {% else %}
                  <li><a href="{% url 'accounts:signup' %}" class="text-white">サインアップ</a></li>
                  <li><a href="{% url 'accounts:login' %}" class="text-white">ログイン</a></li>
                  <li><a href="#" class="text-white">Email me</a></li>
                {% endif %}
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container">
          <a href="{% url 'photo:index' %}" class="navbar-brand d-flex align-items-center">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2" viewBox="0 0 24 24"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>
            <strong>Photo Gallery</strong>
          </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
      </div>
    </header>

    <main>
    {% block contents %}{% endblock %}
    </main>

    <footer class="text-muted py-5">
      <div class="container">
        <p class="float-end mb-1">
          <a href="#">Back to top</a>
        </p>
        <p class="mb-1">Photo Gallery is &copy; Bootstrap, but please post a lot!</p>
      </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

  </body>
</html>

photo/templates/index.html
{% extends 'base.html' %}

{% block title %}Photo Gallery{% endblock %}

{% block contents %}

  {% include 'photos_title.html' %}

  {% include 'photos_list.html' %}
  
{% endblock %}

photo/templates/index_p.html
{% extends 'base_p.html' %}

{% block title %}Photo Gallery{% endblock %}

{% block contents %}

  {% include 'photos_title.html' %}

  {% include 'photos_list.html' %}

{% endblock %}

photo/templates/photos_list.html
<div class="album py-5 bg-light">
  <div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
      <div class="col">
        <div class="card shadow-sm">
          <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false">
            <title>Placeholder</title>
            <rect width="100%" height="100%" fill="#55595c"/>
          </svg>
          <div class="card-body">
            <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
              </div>
              <small class="text-muted">User Name</small>
            </div>
          </div>
        </div>
      </div> 
    </div>
  </div>
</div>

photo/templates/photos_title.html
<section class="py-5 text-center container">
  <div class="row py-lg-5">
    <div class="col-lg-6 col-md-8 mx-auto">
      <h1 class="fw-light">Photo Gallery</h1>
      <p class="lead text-muted">
        コメントを見て写真に描かれた世界に思いを馳せましょう。
        素敵な写真とコメントをお待ちしております！
      </p>
      <p>
        {% if user.is_authenticated %}
          <a href="#" class="btn btn-primary my-2">投稿する</a>
          <a href="{% url 'accounts:logout' %}" class="btn btn-secondary my-2">ログアウト</a>
        {% else %}
          <a href="{% url 'accounts:signup' %}" class="btn btn-primary my-2">サインアップ</a>
          <a href="{% url 'accounts:login' %}" class="btn btn-secondary my-2">ログイン</a>
        {% endif %}
      </p>
    </div>
  </div>
</section>